// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpSS9q0kKoGdjVYmNrxLbrmcvkk9MQoyw',
    appId: '1:650867118338:web:aea3685238d1f362f1721b',
    messagingSenderId: '650867118338',
    projectId: 'tic-tac-toe-863c1',
    authDomain: 'tic-tac-toe-863c1.firebaseapp.com',
    storageBucket: 'tic-tac-toe-863c1.firebasestorage.app',
    measurementId: 'G-77K973151Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBosbpQHbOi2bPbSdGxVb9JiKnfpwwO_CY',
    appId: '1:650867118338:android:868113b271ac9321f1721b',
    messagingSenderId: '650867118338',
    projectId: 'tic-tac-toe-863c1',
    storageBucket: 'tic-tac-toe-863c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIGKlkyAl3gFlMWQf0KaFFiNs27ahUYFc',
    appId: '1:650867118338:ios:b89733a84e12f088f1721b',
    messagingSenderId: '650867118338',
    projectId: 'tic-tac-toe-863c1',
    storageBucket: 'tic-tac-toe-863c1.firebasestorage.app',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIGKlkyAl3gFlMWQf0KaFFiNs27ahUYFc',
    appId: '1:650867118338:ios:b89733a84e12f088f1721b',
    messagingSenderId: '650867118338',
    projectId: 'tic-tac-toe-863c1',
    storageBucket: 'tic-tac-toe-863c1.firebasestorage.app',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpSS9q0kKoGdjVYmNrxLbrmcvkk9MQoyw',
    appId: '1:650867118338:web:42581d09c34db9adf1721b',
    messagingSenderId: '650867118338',
    projectId: 'tic-tac-toe-863c1',
    authDomain: 'tic-tac-toe-863c1.firebaseapp.com',
    storageBucket: 'tic-tac-toe-863c1.firebasestorage.app',
    measurementId: 'G-NCMVDEBJHF',
  );
}
